### ISSUE TITLE
cif-smrt feature: manipulate parsed data 

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/bearded-avenger#10]
How hard would it be to be able manipulate parsed feed data before mapping it to a cif parameter. Here's an example:

cybercrime rss feed:
```
<item>
<title>datatransfer.0xhost.net/25asejd14c2f5r7d4e5f63g2v5d41s/adsf544s2d5f778rg45j6hv32bn41h5j4f/solar/index.php?login</title>
<link>http://cybercrime-tracker.net/index.php</link>
<pubDate>22-07-2015</pubDate>
<description>Solar</description>
</item>
```

The date format is not one DateTime::Format::DateParse; likes. 

It would be neat to be able to do something like this on parsed data:

```
pubDate:
  pattern: '(\S+)'
  subparse: (\d{1,2})-(\d{1,2})-(\d{4})
  new: $3-$2-$1
  values: lasttime
```
