### ISSUE TITLE
Parsing VirusTotal information

### ISSUE THREAD

**Issue by amateur-professional** [csirtgadgets/bearded-avenger#293]
One of our use cases involves polling VirusTotal for some well-known malware names with greater than a certain number of hits and adding them to our threat intel repository. Currently, we have some homebrew scripts accomplishing this for us; however, I'd like to be able to maintain these using CIF instead, to make it easier to add new malwares and adjust the level of positive hits we want. VirusTotal returns API search queries as a single JSON object with the key "hashes", whose value is a list of SHA256 hashes.

My problem is thus: I cannot find any information, on the wiki for v3 or v2, about parsing a JSON list with YAML. Is this a capability of CIF, or do I have to stick to my homebrew scripts?

**Comment by wesyoung** [comment]
i've thought about this off and on, it probably looks something like this [a 'hunter' in v3 speak]:

https://github.com/csirtgadgets/bearded-avenger/blob/master/cif/hunter/farsight.py

where-as `for r in self.client.search(i.indicator):` returns a dict from the VT client, which will then take that info, transform what you want into an indicator object (use `additional_data` as a list for any key-pairs that don't line up).

does that make sense? if you get a branch semi-working we can bat it around till it works...

**Comment by amateur-professional** [comment]
I haven't played much with v3 yet - I take it "hunters" are taking the role of the old cif-worker utility? I was thinking this would work more with a config file for cif-smrt (or whatever the comparable utility is in v3). I'm probably wrong here though :)

Assuming hunters can add data to the store, I think I can get this working.... I'll play around a bit on a separate branch and see what I can do.

**Comment by wesyoung** [comment]
re: hunters vs worker, yes. sort of. we split out "hunters" as "creating new data" vs "gatherers" which are "enriching existing data". meaning 'applying geo information to an indicator' is a gatherer, hunter is "taking a url and creating new FQDN data related to the original url".

as far as "csirtg-smrt" (the new cif-smrt, but not CIF specific anymore), it's only job is taking data in, normalizing it and sending it somewhere else. no more "extra stuff". although, the more i've used it in stand-alone mode, the more i think [somewhere down teh road] adding the concept of hunters too it would be interesting, haven't gotten that far yet. prob a "next version" thing so you'd get the VT information outside of having to throw data into CIF.

my guess is "hunters" will eventually get abstracted out a bit so you can take advantage of them both in csirtg-smrt OR cif (or your own python apps). esp given the way you just talked about them.. seems to make a lot of sense.. (i think?)

**Comment by amateur-professional** [comment]
Got it. Very cool division of work. Would it be appropriate to say hunters still require existing data to work off of? Because I'm not going to have that in this use case.

**Comment by wesyoung** [comment]
yes. the router streams data through it's pipeline and they generate new data from it. the farsight example only looks for searches, which means to test, you should be able to just search `$ cif -q asdfasdfasdfasdf` for a known hash in VT and parse through the responses..

**Comment by amateur-professional** [comment]
This wouldn't work for my use case then, unless I use the homebrew scripts to just get the list of SHA256 hashes and then dump them into CIF - and then let the VirusTotal hunter add more data to it (which actually would work for the second half of my homebrew script that performs the report lookup instead of the search). But I'm trying to make it work with just a simple feed parsing configuration file as a more all-in-one solution.

**Comment by amateur-professional** [comment]
I did notice that the new rule config files enable python code to be executed on config load, and feeds are now able to add filters which essentially act as a way to create URL encoded data. I'm pretty sure I can make this work so long as csirtg-smrt's JSON parser can get me **every hash** out of the list.

**Comment by wesyoung** [comment]
ah, i think i mis-understood what you were trying todo- is it:

+ parse feed of sha256 hashes (not *from* VT)
+ enrich hashes with VT data ?

maybe share a [secret?] gist of your script and we can mock something up? given your second comment it sounds like part of the problem is constructing a specific url for each pull, the second part is mashing that data against VT.

if that's the case; if smrt configs don't do what you need them to, we're messing with the idea around "custom fetchers" that can be called from the config (not 100% yet) but can use this as an example:

https://github.com/csirtgadgets/csirtg-smrt-py/blob/master/csirtg_smrt/fetcher.py#L271
https://github.com/csirtgadgets/apwgsdk-py/blob/master/apwgsdk/client.py#L105

where at-worst, smrt can directly hook into a lib that provides the indicators from your custom feed. we're toying with the idea of calling these "apps" because some of them are custom API integrators to parse data, and some of them also push data out (eg: if you wanted to read custom data from bro and push back out to bro).

[am i getting closer? hard to speculate w/o seeing some of the code]

**Comment by amateur-professional** [comment]
Here's a censored version of our current script: https://gist.github.com/amateur-professional/9c9bff520c305211df0a5109a2ed0d45

We are making a query for a set of VT hashes using their private API search function. This gives us a single JSON object as a response, which has a key named "hashes" whose value is an array of SHA256 hashes that match our search query (detections containing a specific malware name with more than 7 hits, analyzed in the past hour). That second part of the script, getting a report for each of the hashes we found, can probably be done by a Hunter instead of by smrt config. But from my understanding of smrt configs, JSON keys match one-to-one with values for indicators.

**Comment by amateur-professional** [comment]
So for example, here would be my (hopefully working) smrt config to grab the initial set of hashes using the search function, looking for the "3Para" malware with more than 7 hits analyzed in the past hour. 

```
parser: json

defaults:
  provider: virustotal.com
  altid_tlp: white
  altid: https://www.virsutotal.com/en/file/{indicator}/analysis/
  remote: https://www.virustotal.com/vtapi/v2/file/search
  tlp: green
  confidence: 9
  
  map:
    - hashes
  values:
    - indicator
  
feeds:
  3Para:
    filters:
      apikey: 'f3fc0569144b2ed12e89679405f9f5a2557265b0a69261cc1a79a7ea60d3e575'
      query: |
        from datetime import datetime, timedelta
        import urllib
        lastHourDateTime = datetime.utcnow() - timedelta(hours = 1)
        query = urllib.quote_plus("3Para positives:7+ " + lastHourDateTime.strftime('la:%Y-%m-%d %H:%M:%S+ ') + datetime.now().strftime("la:%Y-%m-%dT%H:%M:%S-"))
        print query
```
I just don't know that I will get all of the hashes contained in the array or not.
